import Navbar from "@/components/Layout/Navbar";
import "./globals.css";
import Footer from "@/components/Layout/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <>
        <Navbar />
        {children}
        <Footer />
        </>
      </body>
    </html>
  );
}
